models/Sports.php
<?php

namespace app\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\helpers\Url;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;
use yii\db\Expression;

use app\models\Trainers;

/**
 * This is the model class for table "sports".
 *
 * @property int $id
 * @property string $name
 * @property string $alias
 * @property string $about
 * @property string $image
 * @property int $created_at
 * @property int $updated_at
 */
class Sports extends \yii\db\ActiveRecord
{
    const IMAGE_PATH = '/uploads/sports/';

    public function getTrainer()
    {
        return $this->hasOne(Trainers::className(), ['id' => 'trainer_id']);
                    // ->from(self::tableName() . ' AS trainer');
    }

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%sports}}';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['about'], 'string'],
            [['trainer_id', 'on_main'], 'integer'],
            [['name', 'alias'], 'string', 'max' => 255],
            [['color'], 'string', 'max' => 9],
            [['image'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg', 'maxSize' => 1024*1024*8],
            [['name'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'alias' => 'Alias',
            'about' => 'Описание',
            'image' => 'Картинка',
            'trainer_id' => 'Тренер',
            'color' => 'Цвет расписания',
            'created_at' => 'Добавлено',
            'updated_at' => 'Изменено',
            'on_main' => 'На главной',
        ];
    }

    public function fileUrl()
    {
        $file = $this->image;
        $url = Url::to('@web' . self::IMAGE_PATH . $file );
        return $url;
    }
}

controllers/SportsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Sports;
use app\models\SportsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\UploadedFile;
use yii\helpers\Inflector;

/**
 * SportsController implements the CRUD actions for Sports model.
 */
class SportsController extends Controller
{
    public function init() {
        parent::init();
        $this->layout = 'admin';
    }
    
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'create', 'update', 'delete', 'view'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['show', 'list'],
                        'allow' => true,
                        'roles' => ['?', '@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Sports models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SportsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all Sports models.
     * @return mixed
     */
    public function actionList()
    {
        $searchModel = new SportsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $this->layout = 'main';
        return $this->render('index_list', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Sports model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Displays a single Sports model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionShow($alias)
    {
        $this->layout = 'main';
        return $this->render('view_site', [
            'model' => $this->findModel($alias),
        ]);
    }

    /**
     * Creates a new Sports model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Sports();

        $IMAGES_FOLDER = Yii::getAlias('@webroot/' . $model::IMAGE_PATH);

        if ($model->load(Yii::$app->request->post())) {
            if(empty($model->alias))
                $model->alias = Inflector::slug($model->name, $replacement = '_', $lowercase = true);
            if($model->validate()){
                $model->image = UploadedFile::getInstance($model, 'image');
                if(!empty($model->image)){
                    $image_name = time() . '_' . $model->alias . '.' . $model->image->extension;
                    $model->image->saveAs($IMAGES_FOLDER . $image_name);
                    $model->image = $image_name;
                }
                if($model->save()){
                    return $this->redirect(['index']);
                };
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Sports model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $image_ = $model->image;
        $IMAGES_FOLDER = Yii::getAlias('@webroot/' . $model::IMAGE_PATH);

        if ($model->load(Yii::$app->request->post())) {
            if($model->validate()){
                if(empty($model->alias))
                    $model->alias = Inflector::slug($model->name, $replacement = '_', $lowercase = true);
                $model->image = UploadedFile::getInstance($model, 'image');
                if(!empty($model->image)){
                    @unlink($IMAGES_FOLDER . $image_);
                    $image_name = time() . '_' . $model->alias . '.' . $model->image->extension;
                    $model->image->saveAs($IMAGES_FOLDER . $image_name);
                    $model->image = $image_name;
                }
                else{
                    $model->image = $image_;
                }
                if($model->save()){
                    return $this->redirect(['index']);
                };
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Sports model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        // $this->findModel($id)->delete();
        $model = $this->findModel($id);
        
        if( $model->image!==''){
            $IMAGES_FOLDER = Yii::getAlias('@webroot/' . $model::IMAGE_PATH);
            @unlink($IMAGES_FOLDER . $model->image);
        }
        $model->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Sports model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Sports the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        $model = Sports::find()->andWhere(['id'=>$id])->orWhere(['alias'=>$id])->one();
        if( $model !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/sports/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;

use app\models\Trainers;

/* @var $this yii\web\View */
/* @var $model app\models\Sports */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="sports-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]) ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'alias')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'about')->widget(\yii2jodit\JoditWidget::className()) ?>

    <div class="row">
        <div class="col-xs-12 col-md-6">
            <?= $form->field($model, 'trainer_id')->dropDownList(
                ArrayHelper::map(Trainers::find()->all(),'id','name'),
                ['prompt'=>'Выберите тренера']
            ) ?>
        </div>
        <div class="col-xs-12 col-md-6">
            <div class="form-group">
                <?= $form->field($model, 'color')->textInput(['maxlength' => true, 'style'=>'border-bottom: 5px solid #CCC']) ?>
            </div>
        </div>
    </div>

    <div class="form-group">
        <?= $form->field($model, 'image')->fileInput() ?>
        <?php
            if($model->image){
                echo Html::img(
                        Html::encode(
                            Url::to('@web' . $model::IMAGE_PATH . $model->image )
                        ), ['style'=>'max-height: 200px;']
                    );
            }
        ?>
    </div>

    <div class="form-group">
        <?= $form->field($model, 'on_main')->checkBox(['selected' => $model->on_main]) ?>
    </div>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<?php 
    $this->registerJs("
        let input_name = '#sports-color';
        let input = $('#sports-color');
        input.ColorPicker({
            color: '#0000ff',
            onBeforeShow: function () {
                if( this.value )
                    $(this).ColorPickerSetColor(this.value);
                
            },
            onShow: function(colpkr) {
                $(colpkr).fadeIn(500);
                return false;
            },
            onHide: function(colpkr) {
                $(colpkr).fadeOut(500);
                return false;
            },
            onSubmit: function(hsb, hex, rgb, el) {
                input.val('#'+hex);
                $(el).ColorPickerHide();
                input.trigger('change');
            },
        });
        $(document).on('change', input_name, function(){
            $(this).css('border-bottom-color', $(this).val());
        });
        $(document).ready(function(){
            if(input.val()){
                input.css('border-bottom-color', input.val());
                input.trigger('change');

            }
        });
    ", View::POS_END);
?>

views/sports/_item.php
<?php
use yii\helpers\Url;
?>
<div class="news-item-v2">
    <div class="news-item-bg-v2 lazy" data-src="<?= $model->fileUrl() ?>"></div>
    <div class="news-item-name-v2"><?= $model->name ?></div>
    <a class="news-item-link-v2 btn btn-danger btn-sm"
        href="<?= Url::toRoute(['sports/show', 'alias'=>$model->alias]) ?>">Подробнее</a>
</div>

views/sports/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\SportsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="sports-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'alias') ?>

    <?= $form->field($model, 'about') ?>

    <?= $form->field($model, 'image') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/sports/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Sports */

$this->title = 'Добавление';
$this->params['breadcrumbs'][] = ['label' => 'Виды спорта', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="sports-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/sports/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use yii\grid\GridView;
use yii\widgets\Pjax;

use app\models\Trainers;
/* @var $this yii\web\View */
/* @var $searchModel app\models\SportsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Виды спорта';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="sports-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Добавить вид спорта', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [

            [
                'attribute' => 'image',
                'format' => 'raw',
                'value' => function($model){
                    if( $model->image ){
                        return Html::img(
                                Html::decode(
                                    Url::to('@web' . $model::IMAGE_PATH . $model->image )
                                ), ['style'=>'height: 60px;']
                            );
                    } 
                    else
                        return '';
                },
                'filter' => false,
                'headerOptions' => ['style' => 'width: 100px'],
                'contentOptions' => ['style' => 'width: 100px;', 'class'=>'text-center'],
            ],
            'name',
            'alias',
            [
                'attribute'=>'color',
                'value'=>function($model){
                    if($model->color)
                        if($model->color && strpos($model->color, '#')!==false && strpos($model->color, '#')==0){
                            return '<div class="color-block-default" style="background:'. $model->color .'"></div>'.$model->color;
                        }
                        else
                            return $model->color;
                    else
                        return $model->color;
                },
                'format'=>'html',
            ],
            [
                'attribute'=>'trainer_id',
                'value'=>'trainer.name',
                'filter'=>ArrayHelper::map(Trainers::find()->all(),'id','name'),
            ],
            [
                'attribute' => 'on_main',
                'format' => 'raw',
                'value' => function($model){
                    if($model->on_main)
                        return '<span class="glyphicon glyphicon-ok" aria-hidden="false"></span>';
                    else
                        return '';
                },
                'contentOptions' => ['style' => 'width: 100px; font-size: 20px;', 'class'=>'text-center text-info'],
                'filter' => array(1 => 'На главной', 0 => 'Прочие' ),
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'contentOptions' => ['style' => 'width: 80px;', 'class'=>'text-center'],
            ],
        ],
    ]); ?>

    <?php Pjax::end(); ?>

</div>

views/sports/index_list.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ListView;

use app\models\Trainers;
use app\models\Sports;

/* @var $this yii\web\View */
/* @var $model app\models\Sports */

$this->title = 'Список дисциплин';
\yii\web\YiiAsset::register($this);
$sports = Sports::find()->all();
?>
<div class="section section-top section-full">
    
        <?= ListView::widget([
            'dataProvider' => $dataProvider,
            'itemView' => '_item',
            'layout'=>"{items}\n<div class='col-xs-12'>{pager}</div>",
            'options'=>[
                'style'=>'width: 100%;',
                'class' => 'news-list-v2',
                'id' => false
            ],
            'itemOptions' => [
                'tag' => false,
            ],
        ]); ?>
    
</div>

views/sports/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Sports */

$this->title = 'Редактирование: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Виды спорта', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Редактирование';
?>
<div class="sports-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/sports/view.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Sports */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Виды спорта', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="sports-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Редактировать', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Вы точно собираетесь удалить запись?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'alias',
            [
                'attribute'=>'color',
                'value'=>function($model){
                    if($model->color)
                        if($model->color && strpos($model->color, '#')!==false && strpos($model->color, '#')==0){
                            return '<div class="color-block-default" style="background:'. $model->color .'"></div>'.$model->color;
                        }
                        else
                            return $model->color;
                    else
                        return $model->color;
                },
                'format'=>'raw',
            ],
            [
                'attribute' => 'trainer_id',
                'value' => function ($model){
                    if($model->trainer_id)
                        return Html::a($model->trainer->name, ['trainers/view', 'id'=>$model->trainer_id]);
                    else
                        return '';
                },
                'filter' => false,
                'format' => ['html'],
            ],
            'about:html',
            [
                'attribute'=>'image',
                'value'=> function($model){
                    if($model->image){
                        return Url::to('@web' . $model::IMAGE_PATH . $model->image );
                    }
                },
                'format' => ['image',['height'=>'200']],
            ],
            'created_at:datetime',
            'updated_at:datetime',
        ],
    ]) ?>

</div>

views/sports/view_site.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;

use app\models\Trainers;

/* @var $this yii\web\View */
/* @var $model app\models\Sports */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Виды спорта', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="section">
    <div class="wrap">

        <div class="section-page">
            <div class="first-section row">
                <div class="col-xs-12 col-md-6" style="padding-bottom: 40px;">
                    <div class="first-text">
                        <p class="h1" style="margin-top: 0;">
                            <?= $model->name ?>
                            <span class="red">Занятия<br>каждую неделю</span>
                        </p>
                        <p class="h3">Узнай даты проведения</p>
                        <a class="btn btn-danger btn-lg" href="<?= Url::toRoute(['schedule/page']) ?>">Расписание</a>
                    </div>
                </div>
                <div class="col-xs-12 col-md-6 text-center">
                <?php if($model->image): ?>
                    <center>
                        <img class="lazy" data-src="<?= $model->fileUrl() ?>" style="max-width: 100%;">
                    </center>
                <?php endif ?>
                </div>
                <div class="content-center col-xs-12" style="margin-top: 40px;">
                    <h1 class="preview-title"><?= $model->name ?> это</h1>
                    <div><?= $model->about ?></div>
                    <hr>
                    <div class="text-left">
                        <a class="btn btn-danger" href="<?= Url::toRoute(['sports/list']) ?>">Возврат к списку дисциплин</a>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

<!-- <div class="section">
    <div class="wrap">

        <div class="section section-discipline section-page">
            <div class="first-section">
                <div class="col-xs-12 col-md-6" style="padding-bottom: 40px;">
                <div class="wrap wrap-full wrap-content flex">
                    <div class="first-text">
                        <p class="h1">
                            <?= $model->name ?>
                            <span class="red">Занятия<br>каждую неделю</span>
                        </p>
                        <p class="h3">Узнай даты проведения</p>
                        <a class="btn btn-danger btn-lg" href="<?= Url::toRoute(['schedule/page']) ?>">Расписание</a>
                    </div>
                </div>
                </div>
                <div class="col-xs-12 col-md-6 text-center">
                <?php if($model->image): ?>
                    <center>
                        <img class="lazy" data-src="<?= $model->fileUrl() ?>" style="max-width: 100%;">
                    </center>
                <?php endif ?>
                </div>
            </div>
        </div>

        <div class="section">
            <div class="wrap wrap-content flex flex-top">
                <div class="content-center">
                    <h1 class="preview-title"><?= $model->name ?> это</h1>
                    <div><?= $model->about ?></div>
                    <hr>
                    <div class="text-center">
                        <a class="btn btn-danger" href="<?= Url::toRoute(['sports/list']) ?>">Возврат к списку дисциплин</a>
                    </div>
                </div>
            </div>
            
        </div>

    </div>
</div> -->