models/Trainers.php
<?php

namespace app\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;
use yii\db\Expression;
use yii\helpers\Url;

/**
 * This is the model class for table "trainers".
 *
 * @property int $id
 * @property string $name
 * @property string $about
 * @property string $image
 * @property int $created_at
 * @property int $updated_at
 */
class Trainers extends \yii\db\ActiveRecord
{
    const IMAGE_PATH = '/uploads/trainers/';
    
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'trainers';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'about'], 'required'],
            [['created_at', 'updated_at', 'on_main'], 'integer'],
            [['about', 'alias'], 'string'],
            [['name'], 'string', 'max' => 255],
            [['color'], 'string', 'max' => 9],
            [['image'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg', 'maxSize' => 1024*1024*8],
            [['name'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Имя',
            'alias' => 'Синоним',
            'about' => 'Описание',
            'image' => 'Картинка',
            'color' => 'Цвет расписания',
            'created_at' => 'Добавлено',
            'updated_at' => 'Изменено',
            'on_main' => 'На главной',
        ];
    }

    public function fileUrl()
    {
        $file = $this->image;
        $url = Url::to('@web' . self::IMAGE_PATH . $file );
        return $url;
    }
}

controllers/TrainersController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Trainers;
use app\models\TraindersSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\UploadedFile;
use yii\helpers\Inflector;

/**
 * TrainersController implements the CRUD actions for Trainers model.
 */
class TrainersController extends Controller
{
    public function init() {
        parent::init();
        $this->layout = 'admin';
    }
    
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'create', 'update', 'delete', 'view'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['show', 'list'],
                        'allow' => true,
                        'roles' => ['?', '@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Trainers models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TraindersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all Trainers models.
     * @return mixed
     */
    public function actionList()
    {
        $searchModel = new TraindersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $this->layout = 'main';
        return $this->render('index_list', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all Trainers models.
     * @return mixed
     */
    public function actionShow($alias)
    {
        $this->layout = 'main';
        return $this->render('view_site', [
            'model' => $this->findModel($alias),
        ]);
    }

    /**
     * Displays a single Trainers model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Trainers model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Trainers();
        $IMAGES_FOLDER = Yii::getAlias('@webroot/' . $model::IMAGE_PATH);

        if ($model->load(Yii::$app->request->post())) {
            if(empty($model->alias))
                $model->alias = Inflector::slug($model->name, $replacement = '_', $lowercase = true);
            if($model->validate()){
                $model->image = UploadedFile::getInstance($model, 'image');
                if(!empty($model->image)){
                    $image_name = time() . '.' . $model->image->extension;
                    $model->image->saveAs($IMAGES_FOLDER . $image_name);
                    $model->image = $image_name;
                }
                if($model->save()){
                    return $this->redirect(['index']);
                };
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Trainers model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $image_ = $model->image;
        $IMAGES_FOLDER = Yii::getAlias('@webroot/' . $model::IMAGE_PATH);

        if ($model->load(Yii::$app->request->post())) {
            if(empty($model->alias))
                $model->alias = Inflector::slug($model->name, $replacement = '_', $lowercase = true);
            if($model->validate()){
                $model->image = UploadedFile::getInstance($model, 'image');
                if(!empty($model->image)){
                    @unlink($IMAGES_FOLDER . $image_);
                    $image_name = time() . '.' . $model->image->extension;
                    $model->image->saveAs($IMAGES_FOLDER . $image_name);
                    $model->image = $image_name;
                }
                else{
                    $model->image = $image_;
                }
                if($model->save()){
                    return $this->redirect(['index']);
                };
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Trainers model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        
        if( $model->image!==''){
            $IMAGES_FOLDER = Yii::getAlias('@webroot/' . $model::IMAGE_PATH);
            @unlink($IMAGES_FOLDER . $model->image);
        }
        $model->delete();
        
        return $this->redirect(['index']);
    }

    /**
     * Finds the Trainers model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Trainers the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        $model = Trainers::find()->andWhere(['id'=>$id])->orWhere(['alias'=>$id])->one();
        if( $model !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/trainers/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\web\View;

/* @var $this yii\web\View */
/* @var $model app\models\Trainers */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="trainers-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]) ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'alias')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'about')->widget(\yii2jodit\JoditWidget::className()) ?>
    
    <div class="row">
        <div class="col-xs-12">
            <div class="form-group">
                <?= $form->field($model, 'image')->fileInput() ?>
                <?php
                    if($model->image){
                        echo Html::img(
                                Html::encode(
                                    Url::to('@web' . $model::IMAGE_PATH . $model->image )
                                ), ['style'=>'max-height: 200px;']
                            );
                    }
                ?>
            </div>
        </div>
    </div>

    <div class="form-group">
        <?= $form->field($model, 'on_main')->checkBox(['selected' => $model->on_main]) ?>
    </div>
    
    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/trainers/_item.php
<?php
use yii\helpers\Url;
?>
<div class="trener trener3">
    <div class="trener-item">
        <div class="trener-text">
            <div class="trener-name"><?= $model->name ?></div>
            <div class="style"></div>
            <!-- <div class="team-prev">
                <div><?= $model->about ?></div>
            </div> -->
        </div>
        <img class="lazy" data-src="<?= $model->fileUrl() ?>" alt="<?= $model->name ?>" title="<?= $model->name ?>">
        <a class="trener-link btn btn-danger" href="<?= Url::toRoute(['trainers/show', 'alias'=>$model->alias]) ?>">Подробнее</a>
    </div>
</div>

views/trainers/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\TraindersSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="trainers-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'about') ?>

    <?= $form->field($model, 'image') ?>

    <?= $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/trainers/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Trainers */

$this->title = 'Добавление';
$this->params['breadcrumbs'][] = ['label' => 'Тренеры', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="trainers-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/trainers/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel app\models\TraindersSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Тренеры';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="trainers-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Добавить тренера', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            // ['class' => 'yii\grid\SerialColumn'],

            [
                'attribute' => 'image',
                'format' => 'raw',
                'value' => function($model){
                    if( $model->image ){
                        return Html::img(
                                Html::decode(
                                    Url::to('@web' . $model::IMAGE_PATH . $model->image )
                                ), ['style'=>'height: 60px;']
                            );
                    } 
                    else
                        return '';
                },
                'filter' => false,
                'headerOptions' => ['style' => 'width: 100px'],
                'contentOptions' => ['style' => 'width: 100px;', 'class'=>'text-center'],
            ],
            'name',
            'alias',
            [
                'attribute' => 'on_main',
                'format' => 'raw',
                'value' => function($model){
                    if($model->on_main)
                        return '<span class="glyphicon glyphicon-ok" aria-hidden="false"></span>';
                    else
                        return '';
                },
                'contentOptions' => ['style' => 'width: 100px; font-size: 20px;', 'class'=>'text-center text-info'],
                'filter' => array(1 => 'На главной', 0 => 'Прочие' ),
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'contentOptions' => ['style' => 'width: 80px;', 'class'=>'text-center'],
            ],
        ],
        'tableOptions' => [
            'class' => 'table table-striped table-bordered table-condensed'
        ],
    ]); ?>

    <?php Pjax::end(); ?>

</div>

views/trainers/index_list.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;
use yii\widgets\ListView;

use app\models\Trainers;
use app\models\Sports;

/* @var $this yii\web\View */
/* @var $model app\models\Sports */

$this->title = 'Список тренеров';
\yii\web\YiiAsset::register($this);

?>
<div class="section section-top section-full">
    
        <div class="news-list-v2">
            <div class="trener-box-list">
                
                <?= ListView::widget([
                        'dataProvider' => $dataProvider,
                        'itemView' => '_item',
                        'layout'=>"{pager}\n{items}",
                        'options'=>[
                            'style'=>'width: 100%; height: auto;',
                            'class' => 'trener-right',
                            'id' => false
                        ],
                        'itemOptions' => [
                            'tag' => false,
                        ],
                    ]); ?>

            </div>
        </div>
    
</div>

views/trainers/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Trainers */

$this->title = 'Редактирование: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Тренеры', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Редактирование';
?>
<div class="trainers-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/trainers/view.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Trainers */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Тренеры', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="trainers-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Редактировать', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Вы точно собираетесь удалить запись?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'about:html',
            [
                'attribute'=>'image',
                'value'=> function($model){
                    if($model->image){
                        return Url::to('@web' . $model::IMAGE_PATH . $model->image );
                    }
                },
                'format' => ['image',['height'=>'200']],
            ],
            'created_at:datetime',
            'updated_at:datetime',
        ],
    ]) ?>

</div>

views/trainers/view_site.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;

use app\models\Sports;

$sport = Sports::find()->where(['trainer_id'=>$model->id])->one();

/* @var $this yii\web\View */
/* @var $model app\models\Sports */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Виды спорта', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="section section-top">
    <div class="wrap">
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-4 team-detail-photo pa-0">
                <img class="lazy img-responsive" data-src="<?= $model->fileUrl() ?>" alt="<?= $model->name ?>">
            </div>
            <div class="col-xs-12 col-sm-6 col-md-8 team-detail-desc">
                <h1 class="team-detail-name trener"><?= $model->name ?></h1>
                <div class="team-detail-discipline">
                    <?php
                        if($sport){
                            echo Html::a($sport->name, Url::toRoute(['sports/show', 'alias'=>$sport->alias]));
                        }
                    ?>
                </div>
                <div class="detail-desc">
                    <?= $model->about ?>
                </div>
                <hr>
                <div class="text-left">
                    <a class="btn btn-danger" href="<?= Url::toRoute(['trainers/list']) ?>">Возврат к списку тренеров</a>
                </div>
            </div>
        </div>
    </div>
</div>